<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>lambdasql-web</AssemblyName>
        <ApplicationIcon>λSQL_SMALL_LOGO.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\LambdaSQL.Core\LambdaSQL.Core.csproj" />
    </ItemGroup>

</Project>
